#pragma config(UART_Usage, UART2, uartNotUsed, baudRate4800, IOPins, None, None)
#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Motor,  port1,           grabR,         tmotorVex393_HBridge, openLoop, reversed)
#pragma config(Motor,  port2,           frontRight,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           backRight,     tmotorVex393_MC29, openLoop, reversed, encoderPort, None)
#pragma config(Motor,  port4,           armL1,         tmotorVex393_MC29, openLoop, reversed)//A
#pragma config(Motor,  port5,           armL2,         tmotorVex393_MC29, openLoop, encoderPort, None)//B
#pragma config(Motor,  port6,           frontLeft,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           backLeft,      tmotorVex393_MC29, openLoop, encoderPort, None)
#pragma config(Motor,  port8,           armR1,         tmotorVex393_MC29, openLoop)//C
#pragma config(Motor,  port9,           armR2,         tmotorVex393_MC29, openLoop, encoderPort, None)//D
#pragma config(Motor,  port10,          grabL,         tmotorVex393_HBridge, openLoop, encoderPort, None)
#pragma config(DatalogSeries, 0, "", Motors, MotorPWM, port5, 50)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*#pragma config(Sensor, I2C_1,  backRIME,       sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_2,  backLIME,       sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_3,  armLIME,        sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_4,  armRIME,        sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_5,  grabIME,        sensorQuadEncoderOnI2CPort,    , AutoAssign )*/
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//Important Stuff, Don't Mess with!//////
#pragma platform(VEX2)///////////////////
#pragma competitionControl(Competition)//
#include "Vex_Competition_Includes.c"////
/////////////////////////////////////////
void pre_auton()
{
	bStopTasksBetweenModes = true;
	bDisplayCompetitionStatusOnLcd = false;
	resetMotorEncoder(armL2);
	resetMotorEncoder(armR2);
	// All activities that occur before the competition starts
	// Example: clearing encoders, setting servo positions, ...
}
void drive(int speed)//Some of these might need to be made negative
{
	motor [frontLeft] = speed;
	motor [frontRight] = speed;
	motor [backRight] = speed;
	motor [backLeft] = speed;
}
void rotate(int speed)
{
	motor [frontLeft] = speed;
	motor [frontRight] = -speed;
	motor [backRight] = -speed;
	motor [backLeft] = speed;
}

void arm (int speed)//fallback simple method
{
	motor [armL1] = speed;
	motor [armL2] = speed;
	motor [armR1] = speed;
	motor [armR2] = speed;
}
void grab (int speed)
{
	motor [grabL] = motor[grabR] = speed;
}
task autonomous()
{

	grab(127);//clutch preload
	wait1Msec(1000);
	grab(0);
	arm(127);//lift arm
	wait1Msec(750);
	arm(0);
	drive(127);//drive short forward
	wait1Msec(750);
	rotate(127);//rotate around
	wait1Msec(740);
	rotate(0);
	drive(-127);//drive backwards
	wait1Msec(500);
	drive(0);
	arm(127);//raise arm full height
	wait1Msec(1500);
	arm(0);
	grab(-127);//release star
	wait1Msec(1200);
	grab(0);
	wait1Msec(10);

	/*rotate(127);
	wait1Msec(2000);
	rotate(0);
	wait1Msec(10);*/

}
task usercontrol()
{
	while (true)
	{
		float x1 = vexRT[Ch4];
		float y1 = vexRT[Ch3];
		float x2 = vexRT[Ch1];
		float y2 = vexRT[Ch2];
		//Left Joystick Arcade Drive///
		motor [frontLeft] = y1 + x1;///
		motor [backLeft] = y1 + x1;////
		motor [frontRight] = y2 - x2;//
		motor [backRight]  = y2 - x2;//
		//////////////////////////////
		//Arm Control/////////////////
		if (vexRT[Btn6U] == 1)			//
		{														//
			arm(127);									//
		}														//
		else if (vexRT[Btn6D] == 1 )//
		{														//
			arm(-127);								//
		}														//
		else												//
		{														//
			arm(0);										//
		}
			//
		//////////////////////////////
		//Grabber Control/////////////
		if (vexRT[Btn8U] == 1)			//
		{														//
			grab(127);								//
		}														//
		else if (vexRT[Btn8D] == 1 )//
		{														//
			grab(-127);								//
		}														//
		else												//
		{														//
			grab(0);									//
		}														//
		//////////////////////////////
		//Deadband////////////////////
		int deadBand = 10;
		if(x1 > deadBand || x1 < -deadBand)
		{
			x1 = x1;
		}
		else
		{
			x1 = 0;
		}
		if(y1 > deadBand || y1 < -deadBand)
		{
			y1 = y1;
		}
		else
		{
			y1 = 0;
		}
		if(x2 > deadBand || x2 < -deadBand)
		{
			x2 = x2;
		}
		else
		{
			x2 = 0;
		}
		if(y2 > deadBand || y2 < -deadBand)
		{
			y2 = y2;
		}
		else
		{
			y2 = 0;
		}
	}
}
