#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, dgtl1,  PELevel,        sensorDigitalIn)
#pragma config(Sensor, I2C_1,  leftE,          sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_2,  lArmE,          sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_3,  rArmE,          sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_4,  rightE,         sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Motor,  port1,           grabR,         tmotorVex393_HBridge, openLoop, reversed)
#pragma config(Motor,  port2,           armR3,         tmotorVex393_MC29, openLoop, encoderPort, I2C_3)
#pragma config(Motor,  port3,           right,         tmotorVex393_MC29, openLoop, driveRight, encoderPort, I2C_4)
#pragma config(Motor,  port4,           armL1,         tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           armL2,         tmotorVex393_MC29, openLoop, encoderPort, None)
#pragma config(Motor,  port6,           armL3,         tmotorVex393_MC29, openLoop, reversed, encoderPort, I2C_2)
#pragma config(Motor,  port7,           left,          tmotorVex393_MC29, openLoop, driveLeft, encoderPort, I2C_1)
#pragma config(Motor,  port8,           armR1,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           armR2,         tmotorVex393_MC29, openLoop, reversed, encoderPort, None)
#pragma config(Motor,  port10,          grabL,         tmotorVex393_HBridge, openLoop, reversed, encoderPort, None)
#pragma config(DatalogSeries, 0, "Battery Status", Sensors, Sensor, in8, 500)
#pragma config(DatalogSeries, 1, "Battery Level", Properties, immediateBatteryLevel, , 500)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//Important Stuff, Don't Mess with!//////
#pragma platform(VEX2)///////////////////
#pragma competitionControl(Competition)//
#include "Vex_Competition_Includes.c"////
/////////////////////////////////////////
void pre_auton()
{
	bLCDBacklight = true;                                    // Turn on LCD Backlight
	bStopTasksBetweenModes = true;
	bDisplayCompetitionStatusOnLcd = false;
	clearLCDLine(0);                                            // Clear line 1 (0) of the LCD
	clearLCDLine(1);                                            // Clear line 2 (1) of the LCD
	string mainBattery;
	if(nImmediateBatteryLevel/1000.0>7)
	{
		displayLCDString(0, 0, "Systems GREEN");
		displayLCDString(1, 0, "Ready to Begin!");
	}
	else
	{
		displayLCDString(0, 0, "REPLACE BATT!!!");
		displayLCDString(1, 0, "Main V: ");
		sprintf(mainBattery, "%1.2f%c", nImmediateBatteryLevel/1000.0,'V');
		displayNextLCDString(mainBattery);
	}
}
//auto methods
void drive(int speed, int forHowLong)
{
	do
	{
		setMotorTarget( right, forHowLong, speed, false );
		setMotorTarget( left, forHowLong, speed, false );
	}
	while(!getMotorTargetCompleted(left) && !getMotorTargetCompleted(right));
		motor[left] = motor[right] = 0;
}
void rotateR (int speed, int forHowLong)
{
	do
	{
		setMotorTarget( right, -forHowLong, -speed, false );
		setMotorTarget( left, forHowLong, speed, false );
	}
	while(!getMotorTargetCompleted(left) && !getMotorTargetCompleted(right));
		motor[left] = motor[right] = 0;
}
void rotateL (int speed, int forHowLong)
{
	do
	{
		setMotorTarget( right, forHowLong, speed, false );
		setMotorTarget( left, -forHowLong, -speed, false );
	}
	while(!getMotorTargetCompleted(left) && !getMotorTargetCompleted(right));
		motor[left] = motor[right] = 0;
}

void arm (int speed)//fallback simple method
{
	motor [armL1] = speed;
	motor [armL2] = speed;
	motor [armL3] = speed;
	motor [armR1] = speed;
	motor [armR2] = speed;
	motor [armR3] = speed;
}
void grab (int speed)
{
	motor [grabL] = motor[grabR] = speed;
}
////////////////////////////////////////
//autonomous
task autonomous()
{
	slaveMotor(armL3, armL2);
	slaveMotor(armL2, armL1);
	slaveMotor(armR3, armR2);
	slaveMotor(armR2, armR1);
	grab(127);//clutch preload
	wait1Msec(1250);
	grab(0);
	drive(127, 0); //drive forward, get encoder count
	wait1Msec(1000);
	drive(0, 0);
	wait1Msec(10);

}
task usercontrol()
{
	while (true)
	{
		float x1 = vexRT[Ch4];
		float y1 = vexRT[Ch3];
		float x2 = vexRT[Ch1];
		float y2 = vexRT[Ch2];
		//Left Joystick Arcade Drive//
		motor [left] = y1 + x1;     //
		motor [right]  = y1 - x1;   //
		//////////////////////////////
		//Arm Control/////////////////
		if (vexRT[Btn6U] == 1)			//
		{														//
			arm(127);									//
		}														//
		else if (vexRT[Btn6D] == 1 )//
		{														//
			arm(-127);								//
		}														//
		else												//
		{														//
			arm(0);										//
		}														//
		//////////////////////////////
		//Grabber Control/////////////
		if (vexRT[Btn8U] == 1)			//
		{														//
			grab(127);								//
		}														//
		else if (vexRT[Btn8D] == 1) //
		{														//
			grab(-127);								//
		}														//
		else												//
		{														//
			grab(0);									//
		}														//
		//////////////////////////////
		//LCD Display/////////////////
		string mainBattery, PEBattery;
		clearLCDLine(0);                                            // Clear line 1 (0) of the LCD
		clearLCDLine(1);                                            // Clear line 2 (1) of the LCD

		//Display the Primary Robot battery voltage
		displayLCDString(0, 0, "Primary: ");
		sprintf(mainBattery, "%1.2f%c", nImmediateBatteryLevel/1000.0,'V');
		displayNextLCDString(mainBattery);

		//Display the Backup battery voltage
		displayLCDString(1, 0, "Count: ");
		sprintf(PEBattery, "%1.2f%c", BackupBatteryLevel/1000.0, 'V');
		displayNextLCDString(PEBattery);
		//Deadband////////////////////
		int deadBand = 10;
		if(x1 > deadBand || x1 < -deadBand)
		{
			x1 = x1;
		}
		else
		{
			x1 = 0;
		}
		if(y1 > deadBand || y1 < -deadBand)
		{
			y1 = y1;
		}
		else
		{
			y1 = 0;
		}
		if(x2 > deadBand || x2 < -deadBand)
		{
			x2 = x2;
		}
		else
		{
			x2 = 0;
		}
		if(y2 > deadBand || y2 < -deadBand)
		{
			y2 = y2;
		}
		else
		{
			y2 = 0;
		}
	}
}
