#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, in1,    PEStatus,       sensorAnalog)
#pragma config(Sensor, I2C_1,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_2,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_3,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_4,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Motor,  port1,           grabR,         tmotorVex393_HBridge, openLoop, reversed)
#pragma config(Motor,  port2,           armR3,         tmotorVex393_MC29, PIDControl, reversed, encoderPort, I2C_1)
#pragma config(Motor,  port3,           right,         tmotorVex393_MC29, PIDControl, reversed, driveRight, encoderPort, I2C_2)
#pragma config(Motor,  port4,           armL1,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           armL2,         tmotorVex393_MC29, openLoop, reversed, encoderPort, None)
#pragma config(Motor,  port6,           armL3,         tmotorVex393_MC29, PIDControl, encoderPort, I2C_3)
#pragma config(Motor,  port7,           left,          tmotorVex393_MC29, PIDControl, driveLeft, encoderPort, I2C_4)
#pragma config(Motor,  port8,           armR1,         tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           armR2,         tmotorVex393_MC29, openLoop, encoderPort, None)
#pragma config(Motor,  port10,          grabL,         tmotorVex393_HBridge, openLoop, encoderPort, None)
#pragma config(DatalogSeries, 0, "", Motors, MotorPWM, port5, 50)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//Important Stuff, Don't Mess with!//////
#pragma platform(VEX2)///////////////////
#pragma competitionControl(Competition)//
#include "Vex_Competition_Includes.c"////
/////////////////////////////////////////
void pre_auton()
{
	bLCDBacklight = true;                                    // Turn on LCD Backlight
	string mainBattery, PEBattery;
	bStopTasksBetweenModes = true;
	bDisplayCompetitionStatusOnLcd = false;
	resetMotorEncoder(armL2);
	resetMotorEncoder(armR2);
	clearLCDLine(0);                                            // Clear line 1 (0) of the LCD
	clearLCDLine(1);                                            // Clear line 2 (1) of the LCD

	//Display the Primary Robot battery voltage
	displayLCDString(0, 0, "Primary: ");
	sprintf(mainBattery, "%1.2f%c", nImmediateBatteryLevel/1000.0,'V'); //Build the value to be displayed
	displayNextLCDString(mainBattery);

	//Display the Backup battery voltage
	displayLCDString(1, 0, "Secondary: ");
	sprintf(PEBattery, "%1.2f%c", PEStatus/70, 'V');    //Build the value to be displayed
	displayNextLCDString(PEBattery);
	// All activities that occur before the competition starts
	// Example: clearing encoders, setting servo positions, ...
}
void drive(int speed)//Some of these might need to be made negative
{
	motor [left] = speed;
	motor [right] = speed;
}
void rotate(int speed)
{
	motor [left] = speed;
	motor [right] = -speed;
}

void arm (int speed)//fallback simple method
{
	motor [armL1] = speed;
	motor [armL2] = speed;
	motor [armL3] = speed;
	motor [armR1] = speed;
	motor [armR2] = speed;
	motor [armR3] = speed;
}
void grab (int speed)
{
	motor [grabL] = motor[grabR] = speed;
}
task autonomous()
{
	slaveMotor(armL1, armL2);
	slaveMotor(armL2, armL3);
	slaveMotor(armR1, armR2);
	slaveMotor(armR2, armR3);
	//change this to encoder powered
	grab(127);//clutch preload
	wait1Msec(750);
	grab(0);
	moveMotorTarget(armL2, 197, 127, true);// lift arm a bit
	moveMotorTarget(armR2, 197, 127, true);
	while(!getMotorTargetCompleted(armL2) && !getMotorTargetCompleted(armR2))
		wait1Msec(100);
	drive(127);//drive short forward
	wait1Msec(750);
	rotate(127);//rotate around
	wait1Msec(740);
	rotate(0);
	drive(-127);//drive backwards
	wait1Msec(500);
	drive(0);
	moveMotorTarget(armL2, 197, 127, true);// lift arm fully
	moveMotorTarget(armR2, 197, 127, true);
	while(!getMotorTargetCompleted(armL2) && !getMotorTargetCompleted(armR2))
		wait1Msec(100);
	grab(-127);//release star
	wait1Msec(1200);
	grab(0);
	wait1Msec(10);

	/*rotate(127);
	wait1Msec(2000);
	rotate(0);
	wait1Msec(10);*/

}
task usercontrol()
{
	while (true)
	{
		float x1 = vexRT[Ch4];
		float y1 = vexRT[Ch3];
		float x2 = vexRT[Ch1];
		float y2 = vexRT[Ch2];
		//Left Joystick Arcade Drive///
		motor [left] = y1 + x1;///
		motor [right]  = y2 - x2;//
		//////////////////////////////
		//Arm Control/////////////////
		if (vexRT[Btn6U] == 1)			//
		{														//
			arm(127);									//
		}														//
		else if (vexRT[Btn6D] == 1 )//
		{														//
			arm(-127);								//
		}														//
		else												//
		{														//
			arm(0);										//
		}
		//
		//////////////////////////////
		//Grabber Control/////////////
		if (vexRT[Btn8U] == 1)			//
		{														//
			grab(127);								//
		}														//
		else if (vexRT[Btn8D] == 1 )//
		{														//
			grab(-127);								//
		}														//
		else												//
		{														//
			grab(0);									//
		}														//
		//////////////////////////////
		//LCD Display/////////////////

		//Deadband////////////////////
		int deadBand = 10;
		if(x1 > deadBand || x1 < -deadBand)
		{
			x1 = x1;
		}
		else
		{
			x1 = 0;
		}
		if(y1 > deadBand || y1 < -deadBand)
		{
			y1 = y1;
		}
		else
		{
			y1 = 0;
		}
		if(x2 > deadBand || x2 < -deadBand)
		{
			x2 = x2;
		}
		else
		{
			x2 = 0;
		}
		if(y2 > deadBand || y2 < -deadBand)
		{
			y2 = y2;
		}
		else
		{
			y2 = 0;
		}
	}
}
